CREATE VIEW FIDEMAX_ORDER_ITEMS_PROFESSIONAL AS
SELECT D2_FILIAL AS EMPRESA,D2_DOC AS DOCUMENTO,D2_SERIE AS SERIE,D2_COD AS CODIGO,D2_QUANT AS QUANTIDADE,D2_PRCVEN AS PRECO_VENDA,D2_TOTAL AS TOTAL,
ZFC_PERCEN AS PERCENTUAL_GRUPO,ZFD_FIDPER AS PERCENTUAL_MARCA,D2.R_E_C_N_O_ AS REC
FROM SD2010 (NOLOCK) D2
INNER JOIN SF2010 (NOLOCK) F2 ON F2_FILIAL = D2_FILIAL AND F2_DOC = D2_DOC AND F2_SERIE = D2_SERIE
INNER JOIN ZFB010 (NOLOCK) ZFB ON ZFB_CLIENT = F2_VEND2
INNER JOIN SB1010 (NOLOCK) B1 ON
B1_COD = D2_COD
LEFT JOIN ZFC010 (NOLOCK) ZFC ON
ZFC_GRUPO = B1_GRUPO AND ZFC_FILIAL = D2_FILIAL AND ZFC_CODIGO = ZFB_TIPOCL AND ZFC.D_E_L_E_T_ = ''
LEFT JOIN ZFD010 (NOLOCK) ZFD ON
RTRIM(LTRIM(ZFD_DESCRI)) = RTRIM(LTRIM(B1_MARCA)) AND ZFD_FILIAL = D2_FILIAL AND ZFD_CODIGO = ZFB_TIPOCL AND ZFD.D_E_L_E_T_ = ''
WHERE B1.D_E_L_E_T_ = '' AND D2.D_E_L_E_T_ = '' AND F2.D_E_L_E_T_ = '' AND ZFB.D_E_L_E_T_ = ''